name: "Ensure packages build"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.toml"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.toml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "${{ matrix.version }}"
          override: true
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "tests"
      - uses: "queer/actions/peckish_install@mistress"
      - name: "Build debug binary"
        run: "cargo build"
      - uses: "queer/actions/peckish_run@mistress"
